# Generated by Django 3.1.4 on 2020-12-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emp_image', models.ImageField(upload_to='images/')),
                ('name1', models.CharField(max_length=50)),
                ('emp_image1', models.ImageField(upload_to='images/')),
                ('name2', models.CharField(max_length=50)),
                ('emp_image2', models.ImageField(upload_to='images/')),
                ('name3', models.CharField(max_length=50)),
                ('emp_image3', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
